# Use the official Golang base image
FROM golang:1.17-alpine

# Set the working directory inside the container
WORKDIR /app

COPY go.mod go.sum ./

# Download and cache the Go dependencies
RUN go mod download

# Copy the application source code
COPY . .

# Build the Go application
RUN go build -o receivercmd receiver/main.go

# Expose the port on which the receiver listens
EXPOSE 8002

# Run the receiver executable
CMD ["./receivercmd"]
