# Use the official Golang base image
FROM golang:1.17-alpine

# Set the working directory inside the container
WORKDIR /app

COPY go.mod go.sum ./


# Download and cache the Go dependencies
RUN go mod download

# Copy the application source code
COPY . .

# Build the Go application
RUN go build -o sendercmd sender/main.go

# Expose the port on which the sender listens
EXPOSE 8001

# Run the sender executable
CMD ["./sendercmd"]
